# Generated by Django 4.1.3 on 2022-11-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homeslider_homeslideractive'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomeCategory name')),
            ],
            options={
                'verbose_name': 'HomeCategory',
                'verbose_name_plural': 'HomeCategories',
            },
        ),
        migrations.CreateModel(
            name='HomeSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomeSubCategory name')),
                ('homecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homecateg', to='main.homecategory')),
            ],
            options={
                'verbose_name': 'HomeSubCategory',
                'verbose_name_plural': 'HomeSubCategories',
            },
        ),
    ]
