# Generated by Django 4.1.3 on 2022-11-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homecategory_homesubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Item name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Item image')),
                ('homesubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitem', to='main.homesubcategory')),
            ],
            options={
                'verbose_name': 'SubCategProd',
                'verbose_name_plural': 'SubCategProds',
            },
        ),
    ]
