# Generated by Django 4.1.3 on 2022-11-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subcategprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategprod',
            name='homesubcategory',
        ),
        migrations.AddField(
            model_name='subcategprod',
            name='homesubcategory',
            field=models.ManyToManyField(related_name='subitem', to='main.homesubcategory'),
        ),
    ]
